### ISSUE TITLE
mavlink_connection returns SerialException with COM connection over Bluetooth

### ISSUE THREAD

**Issue by otsuka-kohei** [ArduPilot/pymavlink#261]
Hello.

I am trying to use dronekit-python with Bluetooth teremetry on windows.
But dronekit-python returns error bellow.
```
Traceback (most recent call last):
  File ".\receiver.py", line 173, in <module>
    main()
  File ".\receiver.py", line 140, in main
    drone = connect_drone()
  File ".\receiver.py", line 23, in connect_drone
    heartbeat_timeout=300)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\dronekit-2.9.1-py3.7.egg\dronekit\__init__.py", line 3152, in connect
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\dronekit-2.9.1-py3.7.egg\dronekit\mavlink.py", line 130, in __init__
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 1638, in mavlink_connection
    force_connected=force_connected)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 917, in __init__
    raise e
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 914, in __init__
    dsrdtr=False, rtscts=False, xonxoff=False)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com6': OSError(22, 'Element not found.', None, 1168)
```
  
To research cause, I wrote and execute simple pyserial code.
```
import serial
import time
s = serial.Serial()
s.baudrate = 56700
s.port = 'com6'
s.open()
time.sleep(10)
s.close()
s = serial.Serial("com6", 1200, timeout=0, dsrdtr=False, rtscts=False, xonxoff=False)
time.sleep(10)
s.close()
```
But it does not return error.

So I think cause is pymavlink, I execute instruction bellow.
`m = mavutil.mavlink_connection("com6", baud=57600)`
And this execution returns error bellow.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 1638, in mavlink_connection
    force_connected=force_connected)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 917, in __init__
    raise e
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 914, in __init__
    dsrdtr=False, rtscts=False, xonxoff=False)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com6': OSError(22, 'The semaphore timeout period has expired.', None, 121)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 1638, in mavlink_connection
    force_connected=force_connected)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 917, in __init__
    raise e
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\pymavlink-2.3.4-py3.7.egg\pymavlink\mavutil.py", line 914, in __init__
    dsrdtr=False, rtscts=False, xonxoff=False)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\otsuka\AppData\Local\Programs\Python\Python37\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com6': OSError(22, 'Element not found.', None, 1168)
```
  
Mission Planner can connect without some error.
Could you tell me some solution?
  
Environment list
- WIndows 10 Pro 1809
- pymavlink  2.3.4
- pyserial   3.4
- dronekit-python installed by setup.py
- HC-05 Bluetooth module for Pixhawk
- Intel Wireless Bluetooth on PC

**Comment by otsuka-kohei** [comment]
When run `m = mavutil.mavlink_connection("com6", baud=57600)`, Python executes

**Comment by otsuka-kohei** [comment]
I installed pymavlink with setup.py of dronekit-python.

**Comment by otsuka-kohei** [comment]
I found a solution.
But why it is cause this problem.

`mavlink_connection`on`mavutil.py`, comment out bellow.
```
def mavlink_connection(device, baud=115200, source_system=255, source_component=0,
                       planner_format=None, write=False, append=False,
                       robust_parsing=True, notimestamps=False, input=True,
                       dialect=None, autoreconnect=False, zero_time_base=False,
                       retries=3, use_native=default_native,
                       force_connected=False, progress_callback=None):
    '''open a serial, UDP, TCP or file mavlink connection'''
    global mavfile_global

    if force_connected:
        # force_connected implies autoreconnect
        autoreconnect = True

    if dialect is not None:
        set_dialect(dialect)
    if device.startswith('tcp:'):
        return mavtcp(device[4:],
                      autoreconnect=autoreconnect,
                      source_system=source_system,
                      source_component=source_component,
                      retries=retries,
                      use_native=use_native)
    if device.startswith('tcpin:'):
        return mavtcpin(device[6:], source_system=source_system, source_component=source_component, retries=retries, use_native=use_native)
    if device.startswith('udpin:'):
        return mavudp(device[6:], input=True, source_system=source_system, source_component=source_component, use_native=use_native)
    if device.startswith('udpout:'):
        return mavudp(device[7:], input=False, source_system=source_system, source_component=source_component, use_native=use_native)
    if device.startswith('udpbcast:'):
        return mavudp(device[9:], input=False, source_system=source_system, source_component=source_component, use_native=use_native, broadcast=True)
    # For legacy purposes we accept the following syntax and let the caller to specify direction
    if device.startswith('udp:'):
        return mavudp(device[4:], input=input, source_system=source_system, source_component=source_component, use_native=use_native)
    if device.startswith('mcast:'):
        return mavmcast(device[6:], source_system=source_system, source_component=source_component, use_native=use_native)

    if device.lower().endswith('.bin') or device.lower().endswith('.px4log'):
        # support dataflash logs
        from pymavlink import DFReader
        m = DFReader.DFReader_binary(device, zero_time_base=zero_time_base, progress_callback=progress_callback)
        mavfile_global = m
        return m

    if device.endswith('.log'):
        # support dataflash text logs
        from pymavlink import DFReader
        if DFReader.DFReader_is_text_log(device):
            m = DFReader.DFReader_text(device, zero_time_base=zero_time_base, progress_callback=progress_callback)
            mavfile_global = m
            return m    

    # list of suffixes to prevent setting DOS paths as UDP sockets
    logsuffixes = ['mavlink', 'log', 'raw', 'tlog' ]
    suffix = device.split('.')[-1].lower()
    if device.find(':') != -1 and not suffix in logsuffixes:
        return mavudp(device, source_system=source_system, source_component=source_component, input=input, use_native=use_native)

    # comment out from here
    """
    if os.path.isfile(device):
        if device.endswith(".elf") or device.find("/bin/") != -1:
            print("executing '%s'" % device)
            return mavchildexec(device, source_system=source_system, source_component=source_component, use_native=use_native)
        elif not write and not append and not notimestamps:
            return mavmmaplog(device, progress_callback=progress_callback)
        else:
            return mavlogfile(device, planner_format=planner_format, write=write,
                              append=append, robust_parsing=robust_parsing, notimestamps=notimestamps,
                              source_system=source_system, source_component=source_component, use_native=use_native)
    """
    # to here
    
    return mavserial(device,
                     baud=baud,
                     source_system=source_system,
                     source_component=source_component,
                     autoreconnect=autoreconnect,
                     use_native=use_native,
                     force_connected=force_connected)
```

By my simple research, `if os.path.isfile(device):` is cause this problem.
I wrote 
```
if os.path.isfile(device):
        pass
```
instead of comment outed part.
And program returns same SerialException.
I cannot understand why it is cause.
