### ISSUE TITLE
No such file or directory:message_definitions/v1.0/ardupilotmega.xml

### ISSUE THREAD

**Issue by roseyangyu** [ArduPilot/pymavlink#309]
WARNING: Unable to load XML validator libraries. XML validation will not be performed
ERROR:dronekit.mavlink:Exception while receiving message: 
Traceback (most recent call last):
  File "dronekit-python/dronekit/mavlink.py", line 218, in mavlink_thread_in
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/mavutil.py", line 1061, in recv_msg
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/mavutil.py", line 267, in auto_mavlink_version
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/mavutil.py", line 101, in set_dialect
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/generator/mavgen.py", line 241, in mavgen_python_dialect
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/generator/mavgen.py", line 136, in mavgen
  File "pymavlink-2.3.4-py2.7-linux-aarch64.egg/pymavlink/generator/mavgen.py", line 105, in mavgen_validate
IOError: [Errno 2] No such file or directory: '../../../../tmp/_MEIzZzD6G/message_definitions/v1.0/ardupilotmega.xml'

**Comment by roseyangyu** [comment]
I have installed pymavlink==2.3.4 by "pip install pymavlink==2.3.4"

**Comment by auturgy** [comment]
Try sudo pip install -U pymavlink==2.3.4

**Comment by roseyangyu** [comment]
> Try sudo pip install -U pymavlink==2.3.4
> […](#)
> On 29 Apr 2019, at 5:14 pm, Elite yang ***@***.***> wrote: I have installed pymavlink==2.3.4 by "pip install pymavlink==2.3.4" — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I have tried.Same erros

**Comment by roseyangyu** [comment]
Use "sudo MDEF=PATH_TO_message_definitions pip2 install . -vsudo MDEF=PATH_TO_message_definitions pip2 install . -v",it has error as "No XML message definitions found"

**Comment by Huibean** [comment]
define MDEF with the right directory

**Comment by roseyangyu** [comment]
Mavlink1 has not error.But mavlink2 still doesn't solve

**Comment by amilcarlucas** [comment]
Retest it with pymavlink 2.4.11 and reopen if it still does not work
