### ISSUE TITLE
import mavutil problem

### ISSUE THREAD

**Issue by DonatelloX** [ArduPilot/pymavlink#565]
I have a problem with:
`from pymavlink import mavutil`
in python. In particular, the following exception is shown:
```
Traceback (most recent call last):
  File "/home/pi/pymavlink/mavutil.py", line 118, in set_dialect
    mod = __import__(modname)
ModuleNotFoundError: No module named 'pymavlink.dialects.v10.ardupilotmega'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pymav.py", line 6, in <module>
    from pymavlink import mavutil
  File "/home/pi/pymavlink/mavutil.py", line 131, in <module>
    set_dialect(os.environ['MAVLINK_DIALECT'])
  File "/home/pi/pymavlink/mavutil.py", line 122, in set_dialect
    mavgen_python_dialect(dialect, wire_protocol)
  File "/home/pi/pymavlink/generator/mavgen.py", line 333, in mavgen_python_dialect
    if not mavgen(opts, [xml]):
  File "/home/pi/pymavlink/generator/mavgen.py", line 231, in mavgen
    if not mavgen_validate(fname):
  File "/home/pi/pymavlink/generator/mavgen.py", line 200, in mavgen_validate
    with open(xmlfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'message_definitions/v1.0/ardupilotmega.xml'
```
For the pymavlink installation, I used a Raspberry with Raspberry OS and the commands:
```
sudo apt-get install gcc python3-dev libxml2-dev libxslt-dev
sudo apt-get install python3-numpy python3-pytest
sudo python -m pip install --upgrade future lxml
sudo python -m pip install --upgrade pymavlink
```
with no error.

Please, can someone help me?
Thank you

**Comment by peterbarker** [comment]
On Tue, 22 Jun 2021, DonatelloX wrote:

> I have a problem with:
> from pymavlink import mavutil
> in python. In particular, the following exception is shown:

It looks like you've both got a clone of the repo *and* an install using 
pip.

That seldom ends well.

If you were to do that import above from /tmp I suspect it would work - 
you're getting pymavlink all confused about what's coming from where when 
doing that in your home directory.
