### ISSUE TITLE
Problem with installing mavlink

### ISSUE THREAD

**Issue by YairMZ** [ArduPilot/pymavlink#581]
I tried today to add automated testing to my code via github actions.
Within the workflow yml file I attempted to install pymavlink as it is a dependency by: `pip install pymavlink`. The install fails (thus failing the test), and I get the following message. On my computer I have no problem installing and using pymavlink.   
Any idea where does it go wrong? Other dependencies install just fine.

```
Collecting pymavlink
  Downloading pymavlink-2.4.15.tar.gz (4.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.9.6/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-047egyjl/pymavlink_7e0b5e7b466944be91452eddcdd6178d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-047egyjl/pymavlink_7e0b5e7b466944be91452eddcdd6178d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b0fdy3k9
         cwd: /tmp/pip-install-047egyjl/pymavlink_7e0b5e7b466944be91452eddcdd6178d/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /opt/hostedtoolcache/Python/3.9.6/x64/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-wplxl1cu/future_56a7481b2dba4c6881900b9c5ab8a00d/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-wplxl1cu/future_56a7481b2dba4c6881900b9c5ab8a00d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wh6js08j
           cwd: /tmp/pip-wheel-wplxl1cu/future_56a7481b2dba4c6881900b9c5ab8a00d/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for future
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.6/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_2o1olp7', '--quiet', 'future']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-047egyjl/pymavlink_7e0b5e7b466944be91452eddcdd6178d/setup.py", line 109, in <module>
        setup (name = 'pymavlink',
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/opt/hostedtoolcache/Python/3.9.6/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_2o1olp7', '--quiet', 'future']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5f/4e/985824701e53ec259d3898eb71c4d9211e643dd986ce74b8c71a32d6437c/pymavlink-2.4.15.tar.gz#sha256=7bf45ad4a250e5e9928c33b5ff56afed4dbc6f99c8f58d05051e2a308150db80 (from https://pypi.org/simple/pymavlink/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

For completeness here is my complete workflow file:

```
name: NR Error Correction

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pymavlink
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest
```

**Comment by YairMZ** [comment]
This is the log file from the run.
[3_Set up Python 3.9.txt](https://github.com/ArduPilot/pymavlink/files/7110748/3_Set.up.Python.3.9.txt)

**Comment by YairMZ** [comment]
Solved.
I was stupid.
Forgot to add `pip install wheel` in yml file first.
I'll leave it here in case someone else stumbles upon this.
