### ISSUE TITLE
Error while running 'make px4_sitl jmavsim'

### ISSUE THREAD

**Issue by Sanidhya-30** [ArduPilot/pymavlink#696]
[24/851] Generating Mavlink developmen...ssage_definitions/v1.0/development.xml
Traceback (most recent call last):
  File "/home/lucifer/PX4-Autopilot/src/modules/mavlink/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/lucifer/PX4-Autopilot/src/modules/mavlink/mavlink/pymavlink/generator/mavgen.py", line 26, in <module>
    from future import standard_library

ModuleNotFoundError: No module named 'future'

[36/851] Building CXX object msg/CMake...topics_sources/actuator_controls.cpp.o
FAILED: mavlink/development/development.h 

cd /home/lucifer/PX4-Autopilot/build/px4_sitl_default/src/modules/mavlink && /usr/bin/python3 /home/lucifer/PX4-Autopilot/src/modules/mavlink/mavlink/pymavlink/tools/mavgen.py --lang C --wire-protocol 2.0 --output /home/lucifer/PX4-Autopilot/build/px4_sitl_default/mavlink /home/lucifer/PX4-Autopilot/src/modules/mavlink/mavlink/message_definitions/v1.0/development.xml

[50/851] Generating px4 event json file from source
ninja: build stopped: subcommand failed.
Makefile:235: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1

**Comment by peterbarker** [comment]
Install the `future` module for Python.  This really ought to be in the PX4 instructions and/or scripts somewhere....
