### ISSUE TITLE
pip2 upgrade from 2.4.33 to 2.4.34 fails

### ISSUE THREAD

**Issue by impala454** [ArduPilot/pymavlink#722]
Ubuntu 18.04.6
Python 2.7.17
pip 20.3.4
currently installed pymavlink: 2.4.33

```pip2 install -U pymavlink```

gives me:

```
Collecting pymavlink
  Using cached pymavlink-2.4.34.tar.gz (10.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpl95JhP
       cwd: /tmp/pip-install-5M6PY_/pymavlink
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 108, in <module>
      with open("README.md", "r", encoding = "utf-8") as fh:
  TypeError: 'encoding' is an invalid keyword argument for this function
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpl95JhP Check the logs for full command output.
```   
   
I suspect this is the offending change: https://github.com/ArduPilot/pymavlink/commit/046ffa432928010ea051e74aec6f345e7cb9136a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R108

**Comment by khancyr** [comment]
Hello,
thanks the for the report. We are working on a fix and will deploy a new release !
