### ISSUE TITLE
Exception in mavutil.py after bad_data multi-instance message

### ISSUE THREAD

**Issue by clydemcqueen** [ArduPilot/pymavlink#807]
Summary:

For multi-instance message types, e.g., https://mavlink.io/en/messages/common.html#DISTANCE_SENSOR, a call to `add_message` with a `bad_data` message will fail to initialize the `messages[mtype]._instances` dictionary. The next good message after that will cause an exception.

Traceback:

```
$ mavlogdump.py --quiet --types DISTANCE_SENSOR ~/Desktop/sa_tests/2023_04_18_surftrak3/2023-04-18\ 11-03-34.tlog
Traceback (most recent call last):
  File "/home/clyde/.local/bin/mavlogdump.py", line 242, in <module>
    m = mlog.recv_match(blocking=args.follow, type=match_types)
  File "/home/clyde/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 1633, in recv_match
    m = self.recv_msg()
  File "/home/clyde/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 481, in recv_msg
    self.post_message(msg)
  File "/home/clyde/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 1436, in post_message
    super(mavlogfile, self).post_message(msg)
  File "/home/clyde/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 378, in post_message
    add_message(self.sysid_state[src_system].messages, type, msg)
  File "/home/clyde/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 99, in add_message
    messages[mtype]._instances[instance_value] = msg
TypeError: 'NoneType' object does not support item assignment
```

A possible fix is to [modify the if statement](https://github.com/ArduPilot/pymavlink/blob/v2.4.37/mavutil.py#L93):
```
if mtype not in messages or messages[mtype]._instances is None:
```

Reference this conversation:
https://discuss.bluerobotics.com/t/mavlogdump-py-crashes-while-reading-distance-sensor-msgs-in-some-tlog-files/14228

**Comment by clydemcqueen** [comment]
In my case, all of the BAD_DATA messages are coming from CRC errors caused by a different bug: https://github.com/ArduPilot/pymavlink/issues/237

I have been running this workaround for a while, it works well: `export MAV_IGNORE_CRC=1`

See additional notes here: https://github.com/bluerobotics/BlueOS/issues/1740

**Comment by clydemcqueen** [comment]
The sequence is a bit convoluted. I added some print statements to `add_message` to see what is going on:
```
def add_message(messages, mtype, msg):
    '''add a msg to array of messages, taking account of instance messages'''
    if msg.get_type() == 'BAD_DATA':
        if msg.get_type() != mtype:
            print(f'call to add_message() with msg.get_type()={msg.get_type()}, mtype={mtype}, msg._instance_field {msg._instance_field}, stack trace:')
            traceback.print_stack()
```

When the file is opened `init_arrays` is called and we see situations where msg_type != mtype:
```
(.venv) pymavlink ~/projects/mavlink/pymavlink (clyde_fix_807 *%)$ mavlogdump.py --types DISTANCE_SENSOR ~/dive_logs/seaq_logs/2023_04_18_surftrak3/2023-04-18\ 11-03-34.tlog
call to add_message() with msg.get_type()=BAD_DATA, mtype=DISTANCE_SENSOR, msg._instance_field None, stack trace:
  File "/home/clyde/projects/mavlink/pymavlink/.venv/bin/mavlogdump.py", line 81, in <module>
    mlog = mavutil.mavlink_connection(filename, planner_format=args.planner,
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 2115, in mavlink_connection
    return mavmmaplog(device, progress_callback=progress_callback)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 1495, in __init__
    self.init_arrays(progress_callback)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 1574, in init_arrays
    add_message(self.messages, msg.msgname, m)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 91, in add_message
    traceback.print_stack()
...
```

As a result, the `messages` cache is not initialized correctly.

Then during the `msg_recv` loop, msg_type always == mtype, and it crashes:
```
Traceback (most recent call last):
  File "/home/clyde/projects/mavlink/pymavlink/.venv/bin/mavlogdump.py", line 221, in <module>
    m = mlog.recv_match(blocking=args.follow, type=match_types)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 1671, in recv_match
    m = self.recv_msg()
        ^^^^^^^^^^^^^^^
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 503, in recv_msg
    self.post_message(msg)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 1469, in post_message
    super(mavlogfile, self).post_message(msg)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 408, in post_message
    add_message(self.sysid_state[src_system].messages, m_type, msg)
  File "/home/clyde/projects/mavlink/pymavlink/.venv/lib/python3.12/site-packages/pymavlink/mavutil.py", line 103, in add_message
    messages[mtype]._instances[instance_value] = msg
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
```

**Comment by clydemcqueen** [comment]
Thanks for the notes @ES-Alexander 

I am puzzled by the fact that `mavmmaplog.init_arrays()` calls `add_message()` twice for each message in the file: once via `recv_msg()` and `post_message()` and once directly. (See the note above for the stack traces.)

https://github.com/ArduPilot/pymavlink/blob/b684ea521821b5308ca0d3c394a8c849e898b322/mavutil.py#L1568C1-L1570C1

I don't think we need the second call at all. In the normal case it doesn't cause any harm, but in the `BAD_DATA` case it sets up the condition which causes the crash later. This issue is resolved if I remove the second call.

Am I missing anything? @peterbarker 

This only affects the `mavmmaplog` class, so it won't touch UDP connections.
