### ISSUE TITLE
recv_match() error over UDP connection

### ISSUE THREAD

**Issue by jordancormack** [ArduPilot/pymavlink#882]
I've been using pymavlink to successfully send and receive mavlink messages using a serial connection, and I am trying to move to UDP.

When I try to receive a message using `msg = master.recv_match()` I get the following error:

"data, new_addr = self.port.recvfrom(UDP_MAX_PACKET_LEN)
OSError: [WinError 10022] An invalid argument was supplied"

However, if I send a message immediately before (e.g. `master.mav.heartbeat_send(...)` I don't get an error, and a burst of messages are successfully received, before a pause, and another burst of messages.

**Comment by DevankGarg** [comment]
hi, did u figure out this ?

**Comment by musluogluu** [comment]
I need help for this topic immediately. What do you mean by "I send a message immediately before (e.g. master.mav.heartbeat_send(...)" Can anyone help ???

**Comment by 1Blademaster** [comment]
Bumping this; I've ran into the same error while on Python 3.11.3.

```
DEBUG:fgcs:Trying to setup master with port udpout:127.0.0.1:14550 and baud 115200
ERROR:fgcs:Error while waiting for heartbeat: [WinError 10022] An invalid argument was supplied
Traceback (most recent call last):
  File "E:\projects\FGCS\radio\app\drone.py", line 175, in __init__
    heartbeat = self.master.recv_match(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\FGCS\radio\venv\Lib\site-packages\pymavlink\mavutil.py", line 518, in recv_match
    m = self.recv_msg()
        ^^^^^^^^^^^^^^^
  File "E:\projects\FGCS\radio\venv\Lib\site-packages\pymavlink\mavutil.py", line 1122, in recv_msg
    s = self.recv()
        ^^^^^^^^^^^
  File "E:\projects\FGCS\radio\venv\Lib\site-packages\pymavlink\mavutil.py", line 1080, in recv
    data, new_addr = self.port.recvfrom(UDP_MAX_PACKET_LEN)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by peterbarker** [comment]
@stephendade have you ever seen this?  Looks to be Windows-specific error message.

The odd thing here is that MAVProxy should hit this all the time if you're doing udp - perhaps it's udp-in vs udp-out codepaths?

**Comment by stephendade** [comment]
I'll take a look over the next few days

**Comment by 1Blademaster** [comment]
So I fixed this by sending a heartbeat out to the vehicle before my initial `wait_heartbeat` function (or any `recv_msg` function). But still not sure for the underlying root cause.

**Comment by stephendade** [comment]
I've now had a look at this. It's some interesting Windows-specific behavior.

Python-on-Windows will not initialise the UDP socket until the socket is bound via the ``socket.bind`` method. This does not occur for the ``udpout`` connection type in pymavlink.

A ``socket.send()`` will seemingly call ``socket.bind`` if required. This explains the behavior that ``udpout`` works fine if you send a packet _before_ any receive methods. This includes MAVProxy, which sends out a heartbeat before checking for messages.

Fixed in #1206

**Comment by stephendade** [comment]
PR has been merged, so closing issue as fixed.
