### ISSUE TITLE
Where is `pymavlink.tools.mavgen`?

### ISSUE THREAD

**Issue by tribbloid** [ArduPilot/pymavlink#969]
After upgrading pymavlink to the latest, the script invocation to generate message definition:

```

dialects=("CS")

for i in "${dialects[@]}"; do
  python -m pymavlink.generator.mavgen --lang="$i" --wire-protocol=2.0 ...
```

triggered the following warning:

```
Traceback (most recent call last):
  File "/home/shared/conda/envs/swarm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shared/conda/envs/swarm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shared/conda/envs/swarm/lib/python3.10/site-packages/pymavlink/generator/mavgen.py", line 370, in <module>
    raise DeprecationWarning("Executable was moved to pymavlink.tools.mavgen")
DeprecationWarning: Executable was moved to pymavlink.tools.mavgen
```

But the new file `pymavlink.tools.mavgen` can't be found anywhere, when I try to invoke it instead, I got the following error:

```
  python -m pymavlink.tools.mavgen --lang="$i" --wire-protocol=2.0 ...

 Error while finding module specification for 'pymavlink.tools.mavgen' (ModuleNotFoundError: No module named 'pymavlink.tools')
```

How can I install this module? Is it published in PyPI or conda?

**Comment by DNedic** [comment]
Seconding this issue, I have installed `pymavlink` and all its required dependencies in a venv, and tried running that command using the venv python and am encountering the same problem. It looks like [setup.py](https://github.com/ArduPilot/pymavlink/blob/master/setup.py#L130) was never updated to add the `pymavlink.tools` package.
